config/routes.rb
WishingList::Application.routes.draw do
  get "sessions/new"

  resources :wishes
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin', :to => 'sessions#new' 

end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
  attr_accessible :name

  #----------Validations-----------#
  validates :name, :presence => true
  validates :name, :uniqueness => { :case_sensitive => false }

  #----------Associations-----------#


end
# == Schema Information
#
# Table name: hobbies
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :password
  attr_accessible :email


  #----------Validations-----------#            
  validates :name, :presence => true
  validates :email, :presence => true
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  #----------Associations----------#
  has_many :wishes

  has_many :user_hobbies
  has_many :hobies, :through => :user_hobbies


  #----------Functions-------------#
  # Checking that the password matches the password in User.password
  def self.authenticate(email,password)
    user = User.find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(user,password)
  
  end

  def has_password?(user,submitted_password)
    return true if user.password == submitted_password
  else false
  end



end
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  email      :string(255)     not null
#  password   :string(255)     not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/user_hobby.rb
class UserHobby < ActiveRecord::Base
  attr_accessible :hobby_id, :user_id

  #----------Validations-----------#
  validated :hobby_id, :presence => true
  validated :user_id, :presence => true

  #----------Associations-----------#
  belongs_to :user
  belongs_to :hobby

end
# == Schema Information
#
# Table name: user_hobbies
#
#  id         :integer         not null, primary key
#  user_id    :integer         not null
#  hobby_id   :integer         not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/user_wish.rb
class UserWish < ActiveRecord::Base
  attr_accessible :user_id, :wish_id

  #----------Validations-----------#
  validates :user_id, :presence => true
  validates :wish_id, :presence => true

  #----------Associations-----------#
  belongs_to :user
  belongs_to :wish

end
# == Schema Information
#
# Table name: user_wishes
#
#  id         :integer         not null, primary key
#  user_id    :integer         not null
#  wish_id    :integer         not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/wish.rb
class Wish < ActiveRecord::Base
  attr_accessible :name, :owner_id

  #----------Validations-----------#
  validates :name, :length => {:maximum => 80}
  validates :name, :presence => true

  #----------Associations-----------#
  belongs_to :user
  has_many :wish_assistants
  has_many :assistants, :through => :wish_assistants

end
# == Schema Information
#
# Table name: wishes
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  user_id    :integer         not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/wish_assitant.rb
class WishAssitant < ActiveRecord::Base
  attr_accessible :assistant_id, :wish_id

  #----------Validations-----------#
  validated :assistant_id, :presence => true
  validated :wish_id, :presence => true

  #----------Associations-----------#
  belongs_to :user
  belongs_to :wish
  
end
# == Schema Information
#
# Table name: wish_assitants
#
#  id           :integer         not null, primary key
#  wish_id      :integer         not null
#  assistant_id :integer         not null
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil? 
      flash.now[:error] = "Invalid email/password combination." 
      @title = "Sign in" 
      render 'new'
    else
      flash.now[:error] = "User connected" 
      redirect_to user
    end
  end

  def new

  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign up"
  end

  def show
    @user = User.find(params[:id])
    @user_wishes = @user.wishes
  end

   def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'Wish was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @wishes }
    end
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
    @wish = Wish.find(params[:id])
    @user = User.find(@wish.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @wish }
    end
  end

  # GET /wishes/new
  # GET /wishes/new.json
  def new
    @wish = Wish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @wish }
    end
  end

  # GET /wishes/1/edit
  def edit
    @wish = Wish.find(params[:id])
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(params[:wish])

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, :notice => 'Wish was successfully created.' }
        format.json { render :json => @wish, :status => :created, :location => @wish }
      else
        format.html { render :action => "new" }
        format.json { render :json => @wish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /wishes/1
  # PUT /wishes/1.json
  def update
    @wish = Wish.find(params[:id])

    respond_to do |format|
      if @wish.update_attributes(params[:wish])
        format.html { redirect_to @wish, :notice => 'Wish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @wish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy

    respond_to do |format|
      format.html { redirect_to wishes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WishingList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/main.html.erb
<header> 
  <p>Login Page</p> 
</header>
<div>
  <label>Email: </label>
  <input type="text" name="email" />
</div>
<div>
  <label>Password: </label>
  <input type="text" name="password" />
</div>
<%= link_to 'Login', wishes_path %>

app/views/users/new.html.erb
<header>
<h1><%= @title %></h1>
<div>
  <label>Email: </label>
  <input type="text" name="email" />
</div>
<div>
  <label>Password: </label>
  <input type="text" name="password" />
</div>
<%= link_to 'Login', wishes_path %>
</header>

app/views/users/show.html.erb
<header> 
  <p><%= @user.name %></p> 
</header>
<ul>
<% @user_wishes.each do |wish| %>
<li> <%= wish.name %> </li>
<% end %>
</ul>

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<h1>Listing wishes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wishes.each do |wish| %>
  <tr>
    <td><%= wish.name %></td>
    <td><%= link_to 'Show', wish %></td>
    <td><%= link_to 'Edit', edit_wish_path(wish) %></td>
    <td><%= link_to 'Destroy', wish, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wish', new_wish_path %>

app/views/wishes/new.html.erb
<h1>New wish</h1>

<%= render 'form' %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @wish.name %>
</p>

<p>
  <b>Owner:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>